package com.gabe.splitwatch;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Typeface;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.DateFormat;
import java.util.*;

public class MainActivity extends Activity {
  final ArrayList<TimerSet> sets=new ArrayList<>();
  final ArrayList<Run> runs=new ArrayList<>();
  LinearLayout root; TimerSet active; long start,pausedAt,pausedTotal; boolean running,paused; int index; final ArrayList<Long> laps=new ArrayList<>();
  Handler h=new Handler(Looper.getMainLooper()); TextView clock,current;
  Runnable tick=new Runnable(){public void run(){if(running){clock.setText(fmt(elapsed()));h.postDelayed(this,50);}}};

  public void onCreate(Bundle b){super.onCreate(b);load();home();}
  TextView tv(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(12,10,12,10);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
  LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(22,22,22,22);return l;}
  void show(View v){ScrollView s=new ScrollView(this);s.addView(v);setContentView(s);}

  void home(){h.removeCallbacks(tick);root=col();root.addView(tv("Splitwatch",32,true));root.addView(tv("Custom split stopwatches stored only on this phone.",16,false));Button add=btn("Create split timer");add.setOnClickListener(v->edit(null));root.addView(add);for(TimerSet t:sets){LinearLayout c=col();c.addView(tv(t.name,22,true));c.addView(tv(join(t.splits),15,false));List<Run> rr=forSet(t.id,true);if(!rr.isEmpty())c.addView(tv("Recent "+fmt(rr.get(0).total)+" • Best "+fmt(best(rr).total)+" • Avg "+fmt(avg(rr)),14,false));LinearLayout a=new LinearLayout(this);Button st=btn("Start"),hi=btn("History"),ed=btn("Edit");a.addView(st,new LinearLayout.LayoutParams(0,-2,1));a.addView(hi,new LinearLayout.LayoutParams(0,-2,1));a.addView(ed,new LinearLayout.LayoutParams(0,-2,1));st.setOnClickListener(v->watch(t));hi.setOnClickListener(v->history(t));ed.setOnClickListener(v->edit(t));c.addView(a);root.addView(c);}show(root);}

  void edit(TimerSet old){final EditText name=new EditText(this);name.setHint("Timer name");if(old!=null)name.setText(old.name);final LinearLayout list=col();final ArrayList<EditText> fields=new ArrayList<>();ArrayList<String> src=old==null?new ArrayList<>(Arrays.asList("First split")):new ArrayList<>(old.splits);Runnable render=new Runnable(){public void run(){list.removeAllViews();fields.clear();for(int i=0;i<src.size();i++){final int n=i;LinearLayout row=new LinearLayout(MainActivity.this);EditText e=new EditText(MainActivity.this);e.setText(src.get(i));fields.add(e);row.addView(e,new LinearLayout.LayoutParams(0,-2,1));Button up=btn("↑"),dn=btn("↓"),x=btn("×");up.setEnabled(i>0);dn.setEnabled(i<src.size()-1);up.setOnClickListener(v->{sync(src,fields);Collections.swap(src,n,n-1);this.run();});dn.setOnClickListener(v->{sync(src,fields);Collections.swap(src,n,n+1);this.run();});x.setOnClickListener(v->{sync(src,fields);if(src.size()>1){src.remove(n);this.run();}});row.addView(up);row.addView(dn);row.addView(x);list.addView(row);}}};render.run();LinearLayout p=col();p.addView(tv(old==null?"New timer":"Edit timer",26,true));p.addView(name);p.addView(list);Button add=btn("Add split");add.setOnClickListener(v->{sync(src,fields);src.add("New split");render.run();});p.addView(add);Button save=btn("Save");save.setOnClickListener(v->{sync(src,fields);String nn=name.getText().toString().trim();for(String s:src)if(s.trim().isEmpty()){toast("Every split needs a name");return;}if(nn.isEmpty()){toast("Enter a timer name");return;}if(old==null)sets.add(new TimerSet(UUID.randomUUID().toString(),nn,src));else{old.name=nn;old.splits=new ArrayList<>(src);}persist();home();});p.addView(save);if(old!=null){Button del=btn("Delete timer and history");del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete timer?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{sets.remove(old);runs.removeIf(r->r.setId.equals(old.id));persist();home();}).show());p.addView(del);}Button back=btn("Back");back.setOnClickListener(v->home());p.addView(back);show(p);}
  void sync(ArrayList<String> src,ArrayList<EditText> f){src.clear();for(EditText e:f)src.add(e.getText().toString().trim());}

  void watch(TimerSet t){active=t;running=false;paused=false;index=0;laps.clear();LinearLayout p=col();Button back=btn("← Back");back.setOnClickListener(v->{if(running||paused)confirmDiscard(()->home());else home();});p.addView(back);p.addView(tv(t.name,25,true));clock=tv("00:00.0",52,true);clock.setGravity(Gravity.CENTER);clock.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);p.addView(clock);current=tv(t.splits.get(0),24,true);current.setGravity(Gravity.CENTER);p.addView(current);TextView comp=tv(compareText(t,0,0),14,false);comp.setGravity(Gravity.CENTER);p.addView(comp);LinearLayout acts=new LinearLayout(this);Button startB=btn("Start"),lapB=btn(t.splits.size()==1?"Finish":"Lap"),reset=btn("Reset");lapB.setEnabled(false);acts.addView(startB,new LinearLayout.LayoutParams(0,-2,1));acts.addView(lapB,new LinearLayout.LayoutParams(0,-2,1));acts.addView(reset,new LinearLayout.LayoutParams(0,-2,1));p.addView(acts);LinearLayout rows=col();p.addView(rows);Runnable draw=()->{rows.removeAllViews();long cum=0;for(int i=0;i<t.splits.size();i++){String time="—";if(i<laps.size()){long c=laps.get(i);time=fmt(c-cum);cum=c;}rows.addView(tv((i+1)+". "+t.splits.get(i)+"     "+time,17,i==index&&!(!running&&!paused)));}};draw.run();startB.setOnClickListener(v->{if(!running&&!paused){start=SystemClock.elapsedRealtime();pausedTotal=0;running=true;startB.setText("Pause");lapB.setEnabled(true);h.post(tick);}else if(running){pausedAt=SystemClock.elapsedRealtime();running=false;paused=true;startB.setText("Resume");h.removeCallbacks(tick);}else{pausedTotal+=SystemClock.elapsedRealtime()-pausedAt;running=true;paused=false;startB.setText("Pause");h.post(tick);}});lapB.setOnClickListener(v->{if(!running)return;long e=elapsed();laps.add(e);draw.run();if(index==t.splits.size()-1){running=false;h.removeCallbacks(tick);Run r=new Run(UUID.randomUUID().toString(),t.id,System.currentTimeMillis(),e,new ArrayList<>(t.splits),new ArrayList<>(laps),"");runs.add(r);persist();clock.setText(fmt(e));current.setText("Complete");lapB.setEnabled(false);startB.setEnabled(false);completion(t,r);}else{index++;current.setText(t.splits.get(index));comp.setText(compareText(t,index,e));lapB.setText(index==t.splits.size()-1?"Finish":"Lap");draw.run();}});reset.setOnClickListener(v->{if(running||paused)confirmDiscard(()->watch(t));else watch(t);});show(p);}
  long elapsed(){return SystemClock.elapsedRealtime()-start-pausedTotal-(paused?SystemClock.elapsedRealtime()-pausedAt:0);}
  void completion(TimerSet t,Run r){List<Run> prev=forSet(t.id,true);prev.remove(r);String m="Total: "+fmt(r.total);if(prev.isEmpty())m+="\nFirst completed run.";else m+="\nVs recent: "+delta(r.total-prev.get(0).total)+"\nVs best: "+delta(r.total-best(prev).total)+"\nVs average: "+delta(r.total-avg(prev));EditText note=new EditText(this);note.setHint("Optional note");new AlertDialog.Builder(this).setTitle("Run complete").setMessage(m).setView(note).setNegativeButton("Done",(d,w)->{r.note=note.getText().toString();persist();}).setPositiveButton("History",(d,w)->{r.note=note.getText().toString();persist();history(t);}).show();}
  void confirmDiscard(Runnable go){new AlertDialog.Builder(this).setTitle("Discard this run?").setMessage("Unfinished runs are not saved.").setNegativeButton("Keep timing",null).setPositiveButton("Discard",(d,w)->{running=false;paused=false;h.removeCallbacks(tick);go.run();}).show();}

  void history(TimerSet t){LinearLayout p=col();Button back=btn("← Back");back.setOnClickListener(v->home());p.addView(back);p.addView(tv(t.name+" history",26,true));List<Run> rr=forSet(t.id,false);List<Run> exact=forSet(t.id,true);if(!exact.isEmpty())p.addView(tv("Recent "+fmt(exact.get(0).total)+" • Best "+fmt(best(exact).total)+" • Average "+fmt(avg(exact)),16,true));if(rr.isEmpty())p.addView(tv("No completed runs yet.",17,false));for(Run r:rr){LinearLayout c=col();c.addView(tv(DateFormat.getDateTimeInstance().format(new Date(r.when))+"   "+fmt(r.total),18,true));long prev=0;for(int i=0;i<r.cumulative.size();i++){long ctime=r.cumulative.get(i);c.addView(tv((i+1)+". "+r.names.get(i)+"  "+fmt(ctime-prev)+" ("+fmt(ctime)+")",15,false));prev=ctime;}if(!r.note.isEmpty())c.addView(tv("Note: "+r.note,15,false));Button del=btn("Delete run");del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Delete run?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{runs.remove(r);persist();history(t);}).show());c.addView(del);p.addView(c);}show(p);}

  String compareText(TimerSet t,int i,long e){List<Run> rr=forSet(t.id,true);if(rr.isEmpty())return "No previous runs with these exact splits.";long rec=rr.get(0).cumulative.get(i),be=best(rr).cumulative.get(i),av=0;for(Run r:rr)av+=r.cumulative.get(i);av/=rr.size();return "Recent "+delta(e-rec)+" • Best "+delta(e-be)+" • Avg "+delta(e-av);}
  List<Run> forSet(String id,boolean exact){ArrayList<Run> out=new ArrayList<>();TimerSet t=null;for(TimerSet s:sets)if(s.id.equals(id))t=s;for(Run r:runs)if(r.setId.equals(id)&&(!exact||(t!=null&&r.names.equals(t.splits))))out.add(r);out.sort((a,b)->Long.compare(b.when,a.when));return out;}
  Run best(List<Run> x){Run b=x.get(0);for(Run r:x)if(r.total<b.total)b=r;return b;} long avg(List<Run>x){long s=0;for(Run r:x)s+=r.total;return s/x.size();}
  String fmt(long ms){ms=Math.max(0,ms);long t=ms/100,s=(t/10)%60,m=(t/600)%60,h=t/36000;return h>0?String.format(Locale.US,"%d:%02d:%02d.%d",h,m,s,t%10):String.format(Locale.US,"%02d:%02d.%d",m,s,t%10);} String delta(long d){return(d<0?"−":"+")+fmt(Math.abs(d));} String join(List<String>x){return android.text.TextUtils.join(" → ",x);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

  void persist(){JSONArray ss=new JSONArray(),rr=new JSONArray();try{for(TimerSet t:sets){JSONObject o=new JSONObject();o.put("id",t.id);o.put("name",t.name);o.put("splits",new JSONArray(t.splits));ss.put(o);}for(Run r:runs){JSONObject o=new JSONObject();o.put("id",r.id);o.put("set",r.setId);o.put("when",r.when);o.put("total",r.total);o.put("names",new JSONArray(r.names));o.put("cum",new JSONArray(r.cumulative));o.put("note",r.note);rr.put(o);}}catch(Exception ignored){}getSharedPreferences("data",0).edit().putString("sets",ss.toString()).putString("runs",rr.toString()).apply();}
  void load(){try{SharedPreferences p=getSharedPreferences("data",0);JSONArray ss=new JSONArray(p.getString("sets","[]"));for(int i=0;i<ss.length();i++){JSONObject o=ss.getJSONObject(i);sets.add(new TimerSet(o.getString("id"),o.getString("name"),strings(o.getJSONArray("splits"))));}JSONArray rr=new JSONArray(p.getString("runs","[]"));for(int i=0;i<rr.length();i++){JSONObject o=rr.getJSONObject(i);runs.add(new Run(o.getString("id"),o.getString("set"),o.getLong("when"),o.getLong("total"),strings(o.getJSONArray("names")),longs(o.getJSONArray("cum")),o.optString("note","")));}}catch(Exception ignored){}if(sets.isEmpty())sets.add(new TimerSet(UUID.randomUUID().toString(),"Morning Routine Split",new ArrayList<>(Arrays.asList("Shower","Shave","Change"))));}
  ArrayList<String> strings(JSONArray a)throws Exception{ArrayList<String>x=new ArrayList<>();for(int i=0;i<a.length();i++)x.add(a.getString(i));return x;}ArrayList<Long> longs(JSONArray a)throws Exception{ArrayList<Long>x=new ArrayList<>();for(int i=0;i<a.length();i++)x.add(a.getLong(i));return x;}
  static class TimerSet{String id,name;ArrayList<String> splits;TimerSet(String i,String n,List<String>s){id=i;name=n;splits=new ArrayList<>(s);}}
  static class Run{String id,setId,note;long when,total;ArrayList<String> names;ArrayList<Long> cumulative;Run(String i,String s,long w,long t,List<String>n,List<Long>c,String no){id=i;setId=s;when=w;total=t;names=new ArrayList<>(n);cumulative=new ArrayList<>(c);note=no;}}
}
